# Generated by Django 5.1.5 on 2025-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultparsing',
            name='checked_at',
            field=models.DateTimeField(verbose_name='Время проверки'),
        ),
    ]
